/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pceaturidispensary;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class addmedicine extends javax.swing.JFrame {

    /**
     * Creates new form test1
     */
    public addmedicine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        manufacturer = new javax.swing.JTextField();
        referenceno = new javax.swing.JTextField();
        purchaseddate = new javax.swing.JTextField();
        expirydate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1110, 650));
        setPreferredSize(new java.awt.Dimension(1110, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(51, 126, 70, 22);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("+ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(590, 510, 120, 40);

        back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        back.setText("<-BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(240, 510, 127, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(224, 0, 255));
        jLabel7.setText("+REGISTER  NEW MEDICINE+");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(292, 27, 570, 44);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("REFERENCE NO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(577, 126, 139, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("QUANTITY");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 230, 96, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("PURCHASED DATE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(580, 230, 165, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("MANUFACTURER");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 350, 150, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("EXPIRY DATE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(590, 350, 122, 22);

        cancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(880, 510, 140, 40);

        name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(170, 120, 340, 40);

        quantity.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        quantity.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        getContentPane().add(quantity);
        quantity.setBounds(170, 220, 340, 40);

        manufacturer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        manufacturer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        manufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufacturerActionPerformed(evt);
            }
        });
        getContentPane().add(manufacturer);
        manufacturer.setBounds(230, 340, 300, 40);

        referenceno.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        referenceno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        referenceno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referencenoActionPerformed(evt);
            }
        });
        getContentPane().add(referenceno);
        referenceno.setBounds(740, 120, 320, 40);

        purchaseddate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        purchaseddate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        purchaseddate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseddateActionPerformed(evt);
            }
        });
        getContentPane().add(purchaseddate);
        purchaseddate.setBounds(760, 230, 300, 40);

        expirydate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        expirydate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        expirydate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expirydateActionPerformed(evt);
            }
        });
        getContentPane().add(expirydate);
        expirydate.setBounds(740, 340, 310, 40);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 620, 0, 0);

        jLabel10.setForeground(new java.awt.Color(102, 51, 255));
        jLabel10.setText("Purposely made for PCEA Turi Dispensary by Simon Muiruri");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(430, 590, 350, 20);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-390, -210, 1520, 880);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (name.getText().isEmpty() || referenceno.getText().isEmpty() || quantity.getText().isEmpty() || purchaseddate.getText().isEmpty() || manufacturer.getText().isEmpty() || expirydate.getText().isEmpty() ){
             JOptionPane.showMessageDialog(null, "Please fill in all the blanks", "Error", JOptionPane.ERROR_MESSAGE);
                       
         }else{         
        
        try{
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary" , "root", "");
            String sql =  "insert into medicinestore(name,referenceno,quantity, purchaseddate,manufacturer,expirydate) values (?,?,?,?,?,?)";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, name.getText());
            stmt.setString(2, referenceno.getText());
            try{
                stmt.setInt(3, Integer.parseInt(quantity.getText()));
            }
            catch(NumberFormatException exe){
                JOptionPane.showMessageDialog(null, "Please Check the  Quantity", "Error", JOptionPane.ERROR_MESSAGE);
            }
            stmt.setString(4, purchaseddate.getText());
            stmt.setString(5, manufacturer.getText());
            stmt.setString(6, expirydate.getText());
            
            stmt.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"New Medicine added successfully", "Success",JOptionPane.INFORMATION_MESSAGE);
            hospital addmedicine = new hospital();
            addmedicine.setVisible(false);
            dispose();

        } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Please Check the details as you fill them" , "Error", JOptionPane.ERROR_MESSAGE);
           
           
            Logger.getLogger(addpatients.class.getName()).log(Level.SEVERE, null, ex);
            
           
       }
         }
        
        
        
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        hospital test1 = new hospital();
        test1.setVisible(false);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        name.setText("");
        quantity.setText("");
        quantity.setText("");
        purchaseddate.setText("");
        manufacturer.setText("");
        expirydate.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void manufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufacturerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manufacturerActionPerformed

    private void referencenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referencenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_referencenoActionPerformed

    private void purchaseddateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseddateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchaseddateActionPerformed

    private void expirydateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expirydateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expirydateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addmedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addmedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addmedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addmedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addmedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField expirydate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField manufacturer;
    private javax.swing.JTextField name;
    private javax.swing.JTextField purchaseddate;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField referenceno;
    // End of variables declaration//GEN-END:variables
}
