/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pceaturidispensary;
import pceaturidispensary.hospital;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import static pceaturidispensary.Login.conn;

/**
 *
 * @author hp
 */
public class addpatients extends javax.swing.JFrame {
public static Connection con; 
    /**
     * Creates new form addpatients
     */
    public addpatients() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        residence = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        opd = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        phonenumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1110, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(224, 0, 255));
        jLabel1.setText("+REGISTER A PATIENT+");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(260, 51, 470, 44);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("FULL NAME");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(190, 120, 210, 40);

        fullname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fullname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(fullname);
        fullname.setBounds(430, 120, 540, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("RESIDENCE");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(190, 200, 160, 29);

        residence.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        residence.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(residence);
        residence.setBounds(430, 200, 540, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("AGE");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(190, 290, 160, 29);

        age.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        age.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(age);
        age.setBounds(430, 280, 540, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("GENDER");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(190, 350, 160, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("OUT PATIENT NUMBER");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(190, 470, 290, 29);

        opd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        opd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        opd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opdActionPerformed(evt);
            }
        });
        jPanel2.add(opd);
        opd.setBounds(540, 470, 430, 40);

        back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        back.setText("<-BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back);
        back.setBounds(270, 530, 127, 37);

        add.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add.setText("+ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add);
        add.setBounds(560, 530, 105, 37);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(790, 530, 130, 40);

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        male.setText("MALE");
        jPanel2.add(male);
        male.setBounds(490, 340, 75, 31);

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        female.setText("FEMALE");
        jPanel2.add(female);
        female.setBounds(670, 340, 110, 31);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(40, 30, 0, 0);

        jLabel8.setForeground(new java.awt.Color(102, 51, 255));
        jLabel8.setText("Purposely made for PCEA Turi Dispensary by Simon Muiruri");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(370, 620, 410, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("PHONE NUMBER");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(190, 400, 200, 29);

        phonenumber.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        phonenumber.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        phonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenumberActionPerformed(evt);
            }
        });
        jPanel2.add(phonenumber);
        phonenumber.setBounds(440, 390, 540, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\pceaturidispensary\\image\\stethescope.png")); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(0, -10, 1110, 650);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1110, 650);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public Connection getConnection1(){
    try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary", "root", "");
            return con;
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
}
    
    private void opdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opdActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        hospital addpatients = new hospital();
        addpatients.setVisible(false);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
//        && residence != null && age != null && gender !=null && phonenumber != nullS
         if (fullname.getText().isEmpty() || residence.getText().isEmpty() || age.getText().isEmpty() || opd.getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "Please fill in all the blanks", "Error", JOptionPane.ERROR_MESSAGE);
             
             
         }else{         
        
        try{
            con = getConnection1();
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary" , "root" , "");
            String sql =  "insert into patients(fullname,residence,age,gender,phonenumber,opd) values (?,?,?,?,?,?)";
            //String sql = "insert into patients values(?,?,?,?,?)";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, fullname.getText());
            stmt.setString(2, residence.getText());
            try{
                stmt.setInt(3, Integer.parseInt(age.getText()));
            }
            catch(NumberFormatException exe){
                JOptionPane.showMessageDialog(null, "Please Check the  Age", "Error", JOptionPane.ERROR_MESSAGE);
                
            }
            
            String gender =  null;
            if(male.isSelected()){
                gender = male.getText();
            }
            if(female.isSelected()){
                gender = female.getText();
            }
            stmt.setString(4, gender);
            try{
               
                if (phonenumber.getText().length()<10){
                    JOptionPane.showMessageDialog(null, "Phone Number Too Short", "Check Phone Number", JOptionPane.ERROR_MESSAGE);
                }
                else{
                     stmt.setInt(5, Integer.parseInt(phonenumber.getText()));
                }
            }
           
            catch(NumberFormatException exe){
                JOptionPane.showMessageDialog(null, "Please Check the  Phone number entered", "Error", JOptionPane.ERROR_MESSAGE);
                
            }    
            stmt.setString(6, opd.getText());
            
//            con.close();
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null,"New Patient registered successfully", "Success",JOptionPane.INFORMATION_MESSAGE);
            hospital addpatients = new hospital();
            addpatients.setVisible(false);
            dispose();

        } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Please Check the details as you fill them" , "Error", JOptionPane.ERROR_MESSAGE);
           
           
            Logger.getLogger(addpatients.class.getName()).log(Level.SEVERE, null, ex);
            
           
       }
         }
        


        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fullname.setText(null);
        residence.setText(null);
        age.setText(null);
        
        opd.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void phonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addpatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addpatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addpatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addpatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addpatients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField age;
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fullname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField opd;
    private javax.swing.JTextField phonenumber;
    private javax.swing.JTextField residence;
    // End of variables declaration//GEN-END:variables
}
