/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pceaturidispensary;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author hp
 */
public class insertToPharmarcy extends javax.swing.JFrame {

    /**
     * Creates new form insertToPharmarcy
     */
    public insertToPharmarcy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        selector = new javax.swing.JComboBox<>();
        quantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("SELECT MEDICINE YOU WANT TO ADD TO PHARMARCY");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 350, 16);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("QUANTITY");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 90, 70, 16);

        add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(170, 190, 90, 31);

        selector.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorActionPerformed(evt);
            }
        });
        getContentPane().add(selector);
        selector.setBounds(10, 116, 160, 32);

        quantity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(quantity);
        quantity.setBounds(210, 120, 163, 29);

        jLabel4.setForeground(new java.awt.Color(102, 51, 255));
        jLabel4.setText("Purposely made for PCEA Turi Dispensary by Simon Muiruri");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 240, 360, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\pceaturidispensary\\image\\stethescope.png")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-50, -130, 470, 560);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   public void showtable(){
       try{
           Connection conn;
           Statement st;
           ResultSet rs;
           
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary" , "root", "");
            st = conn.createStatement();
            String s = "select * from medicinestore ORDER BY id DESC";
            rs = st.executeQuery(s);
            while(rs.next()){
                selector.addItem(rs.getString(3));
            }
            
            
        }catch(SQLException e){
            
        } 
   }
    public int getCurrentBalance(int bal){
        try {
          
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary" , "root", "");
            PreparedStatement ps;
            ps = conn.prepareStatement("SELECT * FROM medicinestore WHERE name = ? ");
            ps.setInt(1, bal);
            
          
            ResultSet result = ps.executeQuery();
          
            
            if(result.next()){

               return result.getInt("quantity") ;
                
            }
            return 0;
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(receipt.class.getName()).log(Level.SEVERE, null, ex);
            return 0;
        }
        
    }
public void updateMedicine( int medquantity, String medname){
       
                      
        try {           
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary" , "root", "");
            PreparedStatement ps;
            ps = conn.prepareStatement("UPDATE medicinestore SET quantity = ? WHERE name = ?");
            
            ps.setInt(1, medquantity);
            ps.setString(2, medname);
            
            
          ps.execute();
            
        } catch (SQLException ex) {
            Logger.getLogger(receipt.class.getName()).log(Level.SEVERE, null, ex);

        }
        
        
    }

public int getmedicine(String medname){
       
                      
        try {           
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary" , "root", "");
            PreparedStatement ps;
            ps = conn.prepareStatement("SELECT * FROM medicinestore WHERE name = ?");
            
            ps.setString(1, medname);
            
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                String quantity = rs.getString("quantity");
                int q = Integer.parseInt(quantity);
                return q;
            }
            else{
                return -1;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(receipt.class.getName()).log(Level.SEVERE, null, ex);
            return -2;
        }
        
        
    }
    
    
    
    
    private void Fillcombo(){
        try{
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary" , "root", "");
            String sql = "select * from medicinestore";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            stmt = conn.prepareStatement(sql);
            rs=stmt.executeQuery();
            while (rs.next()){
                String name = rs.getString("name");
                selector.addItem(name);
            }
            
        }catch(SQLException e){
            
        }
    }
    
    private void selectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorActionPerformed
       
    }//GEN-LAST:event_selectorActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        showtable();

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        try{
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary" , "root", "");
            String sql =  "insert into pharmarcy(name,quantity) values (?,?)";
            PreparedStatement stmt = conn.prepareStatement(sql);
            
            String value = selector.getSelectedItem().toString();
            stmt.setString(1, value);
            try{
                stmt.setInt(2, Integer.parseInt(quantity.getText()));
            }
            catch(NumberFormatException exe){
                JOptionPane.showMessageDialog(null, "Please Check the  Quantity", "Error", JOptionPane.ERROR_MESSAGE);
            }
             stmt.executeUpdate();
             JOptionPane.showMessageDialog(null, "Saved", "success", JOptionPane.INFORMATION_MESSAGE);
        }catch(SQLException exe){
             JOptionPane.showMessageDialog(null, exe);
        }
       String medname = selector.getSelectedItem().toString();
       int q_text = Integer.parseInt(quantity.getText());
       
       int newQ = getmedicine(medname) - q_text;
       updateMedicine(newQ, medname);
       medicinestore insertToPharmarcy = new medicinestore();
       insertToPharmarcy.setVisible(true);
       dispose();
       

       
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insertToPharmarcy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insertToPharmarcy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insertToPharmarcy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insertToPharmarcy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insertToPharmarcy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField quantity;
    private javax.swing.JComboBox<String> selector;
    // End of variables declaration//GEN-END:variables
}
