/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pceaturidispensary;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class laboratory extends javax.swing.JFrame {
    double num,ans;
    int calculation;
    public void arthmetic_operations(){
        switch(calculation){
            case 1: //addition
                ans = num + Double.parseDouble(disPrice.getText());
                disPrice.setText(Double.toString(ans));
                break;
        }
    }

    /**
     * Creates new form laboratory
     */
    public laboratory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        selector = new javax.swing.JComboBox<>();
        price = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        screen = new javax.swing.JTextArea();
        receipt = new javax.swing.JButton();
        moremed = new javax.swing.JButton();
        finish = new javax.swing.JButton();
        disPrice = new javax.swing.JTextField();
        print = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 700));
        setPreferredSize(new java.awt.Dimension(1350, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(224, 0, 255));
        jLabel1.setText("PCEA TURI DISPENSARY LABORATORY SERVICES");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 40, 610, 29);

        selector.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorActionPerformed(evt);
            }
        });
        getContentPane().add(selector);
        selector.setBounds(40, 120, 220, 40);

        price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        getContentPane().add(price);
        price.setBounds(350, 120, 200, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("+ADD A SERVICE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(960, 110, 190, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("UPDATE CHARGES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(960, 160, 190, 40);

        screen.setColumns(20);
        screen.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        screen.setRows(5);
        jScrollPane1.setViewportView(screen);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(860, 220, 370, 330);

        receipt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        receipt.setText("RECEIPT");
        receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptActionPerformed(evt);
            }
        });
        getContentPane().add(receipt);
        receipt.setBounds(390, 400, 150, 40);

        moremed.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        moremed.setText("More services?");
        moremed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moremedActionPerformed(evt);
            }
        });
        getContentPane().add(moremed);
        moremed.setBounds(390, 210, 150, 40);

        finish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        finish.setText("Finish");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });
        getContentPane().add(finish);
        finish.setBounds(390, 310, 150, 40);

        disPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        disPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disPriceActionPerformed(evt);
            }
        });
        getContentPane().add(disPrice);
        disPrice.setBounds(390, 490, 150, 40);

        print.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(1070, 570, 120, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setText("<-BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(390, 570, 150, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("TOTAL");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, 470, 90, 17);

        clear.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(910, 570, 120, 40);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-300, -240, 1650, 940);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public int getprice(String service){
       
                      
        try {           
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary" , "root", "");
            PreparedStatement ps;
            ps = conn.prepareStatement("SELECT * FROM laboratory WHERE  service = ?");
            
            ps.setString(1, service);
            
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                String price = rs.getString("charges");
                int pri = Integer.parseInt(price);
                return pri;
            }
            else{
                return -1;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(receipt.class.getName()).log(Level.SEVERE, null, ex);
            return -2;
        }
        
        
    }
public int getservice(String service){
       
                      
        try {           
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary" , "root", "");
            PreparedStatement ps;
            ps = conn.prepareStatement("SELECT * FROM laboratory WHERE service = ?");
            
            ps.setString(1, service);
            
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                String quantity = rs.getString("charges");
                int q = Integer.parseInt(quantity);
                return q;
            }
            else{
                return -1;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(receipt.class.getName()).log(Level.SEVERE, null, ex);
            return -2;
        }
        
        
    }
    
    public void showtable(){
       try{
           Connection conn;
           Statement st;
           ResultSet rs;
           
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary" , "root", "");
            st = conn.createStatement();
            String s = "select * from laboratory ORDER BY id DESC";
            rs = st.executeQuery(s);
            while(rs.next()){
                selector.addItem(rs.getString(2));
            }
            
            
        }catch(SQLException e){
            
        } 
   }
private void Fillcombo(){
        try{
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary" , "root", "");
            String sql = "select * from laboratory";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            stmt = conn.prepareStatement(sql);
            rs=stmt.executeQuery();
            while (rs.next()){
                String name = rs.getString("service");
                selector.addItem(name);
            }
            
        }catch(SQLException e){
            
        }
    }
    private void selectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorActionPerformed
        String service = selector.getSelectedItem().toString();
        ///System.out.println(service);
       //int q_text = Integer.parseInt(price.getText());
       int costi = getprice(service);
       
       String s =Integer.toString(costi);
       price.setText(s);
       disPrice.setText(s);
       if(screen.getText().isEmpty()){
           screen.setText("*******************************************\n");
        screen.setText(screen.getText()+ "\t *PCEA TURI DISPENSARY*\n");
        screen.setText(screen.getText()+ "********************************************\n");
        java.util.Date obj = new java.util.Date();
        String date = obj.toString();
        screen.setText(screen.getText()+"\n\t" +date+"\n\n");
        screen.setText(screen.getText()+"\t Service:" +selector.getSelectedItem()+"\n");
       }
       else{
            screen.setText(screen.getText()+"\t Service:" +selector.getSelectedItem()+"\n");
       }
      
       
       
       
       
    }//GEN-LAST:event_selectorActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        showtable();
        screen.setText("*******************************************\n");
        screen.setText(screen.getText()+ "\t *PCEA TURI DISPENSARY*\n");
        screen.setText(screen.getText()+ "********************************************\n");
        java.util.Date obj = new java.util.Date();
        String date = obj.toString();
        screen.setText(screen.getText()+"\n\t" +date+"\n\n");
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addService laboratory = new addService();
        laboratory.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        updateLabCharges laboratory = new updateLabCharges();
        laboratory.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        //price.setText(selector.getSelectedItem().toString());
        
       //System.out.prinln(q);
       
//       String medname = display.getSelectedItem().toString();
//       int q_text = Integer.parseInt(medquantity.getText());
//       
//       int newQ = getmedicine(medname) - q_text;
//       updateMedicine(newQ, medname);
//       int costi = getprice(medname)*q_text;
//       String testa = Integer.toString(costi);
//       screen_display.setText(testa);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void receiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptActionPerformed
        
        
        screen.setText(screen.getText()+"\t Total cost:" + "Ksh" +disPrice.getText()+"\n");
        screen.setText(screen.getText()+"\t\t Official Stamp \n");
        // TODO add your handling code here:
    }//GEN-LAST:event_receiptActionPerformed

    private void moremedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moremedActionPerformed
        
        num = Double.parseDouble(disPrice.getText());
        calculation =1;
        // TODO add your handling code here:
    }//GEN-LAST:event_moremedActionPerformed

    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed

        if(disPrice.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Cannot be Empty");
        }else{
            arthmetic_operations();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_finishActionPerformed

    private void disPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disPriceActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
    if(screen.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Screen is empty", "error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
            screen.print();

        }catch(Exception exec){

        }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_printActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        hospital laboratory = new hospital();
        laboratory.setVisible(false);
        dispose();
                
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
    disPrice.setText("");
    screen.setText("");
    price.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laboratory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laboratory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laboratory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laboratory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laboratory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JTextField disPrice;
    private javax.swing.JButton finish;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton moremed;
    private javax.swing.JTextField price;
    private javax.swing.JButton print;
    private javax.swing.JButton receipt;
    private javax.swing.JTextArea screen;
    private javax.swing.JComboBox<String> selector;
    // End of variables declaration//GEN-END:variables
}
