/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pceaturidispensary;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class medicinestore extends javax.swing.JFrame {

    /**
     * Creates new form medicinestore
     */
    public medicinestore() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        medicinetable = new javax.swing.JTable();
        insertintopharmarcy = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 700));
        setPreferredSize(new java.awt.Dimension(1350, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        back.setForeground(new java.awt.Color(51, 51, 255));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(40, 20, 163, 67);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(224, 0, 255));
        jLabel1.setText("MEDICINE STORE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 10, 642, 87);

        jScrollPane1.setForeground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        medicinetable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        medicinetable.setForeground(new java.awt.Color(0, 0, 255));
        medicinetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name", "referenceno", "quantity", "purchaseddate", "manufacturer", "expiry", "date"
            }
        ));
        medicinetable.setRowHeight(100);
        jScrollPane1.setViewportView(medicinetable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 1310, 560);

        insertintopharmarcy.setBackground(new java.awt.Color(255, 255, 255));
        insertintopharmarcy.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        insertintopharmarcy.setForeground(new java.awt.Color(51, 51, 255));
        insertintopharmarcy.setText("Add to Pharmarcy");
        insertintopharmarcy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertintopharmarcyActionPerformed(evt);
            }
        });
        getContentPane().add(insertintopharmarcy);
        insertintopharmarcy.setBounds(1040, 10, 240, 37);

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        delete.setForeground(new java.awt.Color(51, 51, 255));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(1040, 60, 240, 37);

        jLabel4.setForeground(new java.awt.Color(102, 51, 255));
        jLabel4.setText("Purposely made for PCEA Turi Dispensary by Simon Muiruri");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 680, 410, 14);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-400, -110, 1750, 810);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 public void showtable(){
     try{
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary" , "root", "");
            PreparedStatement ps = conn.prepareStatement("select * from medicinestore ORDER BY id DESC");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel tm = (DefaultTableModel)medicinetable.getModel();
            tm.setRowCount(0);
            while(rs.next()){
                Object obj[] = {rs.getString("name"), rs.getString("referenceno"), rs.getInt("quantity"), rs.getString("purchaseddate"), 
                    rs.getString("manufacturer"),rs.getString("expirydate"), rs.getString("time")};
                tm.addRow(obj);
            }
        }
        catch(Exception ex){
             JOptionPane.showMessageDialog(this, ex);
        }
 }
    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        hospital medstore = new hospital();
        medstore.setVisible(false);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        showtable();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void insertintopharmarcyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertintopharmarcyActionPerformed
        insertToPharmarcy medicinestore = new insertToPharmarcy();
        medicinestore.setVisible(true);
        dispose();
        

            // TODO add your handling code here:
    }//GEN-LAST:event_insertintopharmarcyActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int row = medicinetable.getSelectedRow();
        String cell = medicinetable.getModel().getValueAt(row, 0).toString();
        String sql = "DELETE  from medicinestore where id = " +cell;
        try{
             Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary" , "root", "");
         PreparedStatement   stmt = conn.prepareStatement(sql);
             stmt.execute();
             JOptionPane.showMessageDialog(null, "Medicine deleted successfully");
             showtable();
        }
        catch (SQLException exe){
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(medicinestore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(medicinestore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(medicinestore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(medicinestore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new medicinestore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton delete;
    private javax.swing.JButton insertintopharmarcy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable medicinetable;
    // End of variables declaration//GEN-END:variables
}
