/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pceaturidispensary;
import java.util.Date;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author hp
 */
public class receipt extends javax.swing.JFrame {
String ritwa;
double num,ans;
    int calculation;
    public void arthmetic_operations(){
        switch(calculation){
            case 1: //addition
                ans = num + Double.parseDouble(screen_display.getText());
                screen_display.setText(Double.toString(ans));
                break;
        }
    }
    
    /**
     * Creates new form receipt
     */
    public receipt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        screen = new javax.swing.JTextArea();
        back = new javax.swing.JButton();
        receipt = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        medquantity = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        display = new javax.swing.JComboBox<>();
        patientname = new javax.swing.JComboBox<>();
        screen_display = new javax.swing.JTextField();
        moremed = new javax.swing.JButton();
        finish = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 700));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(224, 0, 255));
        jLabel1.setText("PCEA TURI DISPENSARY  RECEIPT SYSTEM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(177, 35, 1042, 58);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("ENTER PATIENTS FULL NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 80, 356, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("QUANTITY");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(340, 220, 130, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("ENTER TOTAL COST");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 410, 316, 60);

        fname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        getContentPane().add(fname);
        fname.setBounds(407, 125, 410, 40);

        screen.setColumns(20);
        screen.setFont(new java.awt.Font("Monospaced", 0, 5)); // NOI18N
        screen.setRows(5);
        screen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane1.setViewportView(screen);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(853, 135, 280, 470);

        back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        back.setText("<-BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(57, 495, 127, 40);

        receipt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        receipt.setText("RECEIPT");
        receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptActionPerformed(evt);
            }
        });
        getContentPane().add(receipt);
        receipt.setBounds(340, 500, 150, 40);

        cancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(637, 495, 140, 40);

        clear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(877, 625, 140, 40);

        print.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(1127, 625, 140, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("SELECT MEDICINE");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 190, 170, 30);

        medquantity.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        medquantity.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        medquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medquantityActionPerformed(evt);
            }
        });
        getContentPane().add(medquantity);
        medquantity.setBounds(500, 220, 310, 40);

        ok.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ok.setText("CHARGE");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok);
        ok.setBounds(580, 270, 150, 40);

        display.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        getContentPane().add(display);
        display.setBounds(90, 220, 170, 40);

        patientname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        patientname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientnameActionPerformed(evt);
            }
        });
        getContentPane().add(patientname);
        patientname.setBounds(90, 120, 190, 40);

        screen_display.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        screen_display.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        screen_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screen_displayActionPerformed(evt);
            }
        });
        getContentPane().add(screen_display);
        screen_display.setBounds(360, 420, 430, 40);

        moremed.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        moremed.setText("More Medicine?");
        moremed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moremedActionPerformed(evt);
            }
        });
        getContentPane().add(moremed);
        moremed.setBounds(580, 320, 150, 40);

        finish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        finish.setText("Finish");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });
        getContentPane().add(finish);
        finish.setBounds(580, 370, 150, 40);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 60, 70);

        jLabel4.setForeground(new java.awt.Color(102, 51, 255));
        jLabel4.setText("Purposely made for PCEA Turi Dispensary by Simon Muiruri");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(410, 650, 410, 14);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-390, -260, 1750, 950);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public int getCurrentBalance(int bal){
        try {
          
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary" , "root", "");
            PreparedStatement ps;
            ps = conn.prepareStatement("SELECT * FROM pharmarcy WHERE name = ? ");
            ps.setInt(1, bal);
            
          
            ResultSet result = ps.executeQuery();
          
            
            if(result.next()){

               return result.getInt("quantity") ;
                
            }
            return 0;
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(receipt.class.getName()).log(Level.SEVERE, null, ex);
            return 0;
        }
        
    }

public int getprice(String medname){
       
                      
        try {           
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary" , "root", "");
            PreparedStatement ps;
            ps = conn.prepareStatement("SELECT * FROM pharmarcy WHERE name = ?");
            
            ps.setString(1, medname);
            
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                String price = rs.getString("price");
                int pri = Integer.parseInt(price);
                return pri;
            }
            else{
                return -1;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(receipt.class.getName()).log(Level.SEVERE, null, ex);
            return -2;
        }
        
        
    }
public void updateMedicine( int medquantity, String medname){
       
                      
        try {           
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary" , "root", "");
            PreparedStatement ps;
            ps = conn.prepareStatement("UPDATE pharmarcy SET quantity = ? WHERE name = ?");
            
            ps.setInt(1, medquantity);
            ps.setString(2, medname);
            
            
          ps.execute();
            
        } catch (SQLException ex) {
            Logger.getLogger(receipt.class.getName()).log(Level.SEVERE, null, ex);

        }
        
        
    }
    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        hospital receipt = new hospital();
        receipt.setVisible(false);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void receiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptActionPerformed
        screen.setText("*******************************************************\n");
        screen.setText(screen.getText()+ "\t\t *PCEA TURI DISPENSARY*\n");
        screen.setText(screen.getText()+ "*******************************************************\n");
        Date obj = new Date();
        String date = obj.toString();
        screen.setText(screen.getText()+"\n\t" +date+"\n\n");
        screen.setText(screen.getText()+"\t Patient's name:" +fname.getText()+"\n\n");
        //screen.setText(screen.getText()+ "\t SERVICES OFFERED\n" +otherservices.getText()+"\n");
        screen.setText(screen.getText()+ "\t 1. Laboratory Services [____]\n" );
        screen.setText(screen.getText()+ "\t 2. Nursing & Dressing  [____]\n" );
        screen.setText(screen.getText()+ "\t 3. Post Natal Services [____]\n" );
        screen.setText(screen.getText()+ "\t 4. Anti Natal Services [____]\n" +"\n");
        //screen.setText(screen.getText()+"\t Medicine issued:\n" +medissue.getText()+"\n");
        screen.setText(screen.getText()+"\t Total cost:" + "Ksh" +screen_display.getText()+"\n");
        screen.setText(screen.getText()+"\t\t Official Stamp \n");
        // TODO add your handling code here:
    }//GEN-LAST:event_receiptActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        fname.setText(null);
//        medissue.setText(null);
        screen_display.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        fname.setText(null);
        //medissue.setText(null);
        screen_display.setText(null);
        screen.setText(null);
        medquantity.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
       if(screen.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Screen is empty", "error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
            screen.print();

        }catch(Exception exec){

        }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_printActionPerformed

    private void medquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medquantityActionPerformed

    
    public int getmedicine(String medname){
       
                      
        try {           
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary" , "root", "");
            PreparedStatement ps;
            ps = conn.prepareStatement("SELECT * FROM pharmarcy WHERE name = ?");
            
            ps.setString(1, medname);
            
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                String quantity = rs.getString("quantity");
                int q = Integer.parseInt(quantity);
                return q;
            }
            else{
                return -1;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(receipt.class.getName()).log(Level.SEVERE, null, ex);
            return -2;
        }
        
        
    }
    
    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
       //String medname = mediName.getText();
       String medname = display.getSelectedItem().toString();
       int q_text = Integer.parseInt(medquantity.getText());
       
       int newQ = getmedicine(medname) - q_text;
       updateMedicine(newQ, medname);
       int costi = getprice(medname)*q_text;
       String testa = Integer.toString(costi);
       screen_display.setText(testa);
       //System.out.println(costi);
//       String s = Integer.toString(costi);
//      cost.setText(s);
      
//       System.out.println(cost);
//       int a = Integer.parseInt(cost.getText());
//       costi = a;
     
;       
       //System.out.println(getmedicine(mediName.getText()));
       //System.out.println(display.getSelectedItem().toString());
    
        

    }//GEN-LAST:event_okActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
try{
           Connection conn;
           Statement st;
           ResultSet rs;
           
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary" , "root", "");
            st = conn.createStatement();
            String s = "select * from pharmarcy ORDER BY id DESC";
            rs = st.executeQuery(s);
            while(rs.next()){
                display.addItem(rs.getString(2));
            }
            
            
        }catch(SQLException e){
            
        }
        // displaying patient
        try{
           Connection conn;
           Statement st;
           ResultSet rs;
           
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary" , "root", "");
            st = conn.createStatement();
            String s = "select * from patients ORDER BY id DESC";
            rs = st.executeQuery(s);
            while(rs.next()){
                patientname.addItem(rs.getString(2));
                
            }
            
            
        }catch(SQLException e){
            
        }



// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    private void patientnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientnameActionPerformed
    fname.setText(patientname.getSelectedItem().toString());
// TODO add your handling code here:
    }//GEN-LAST:event_patientnameActionPerformed

    private void screen_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screen_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_screen_displayActionPerformed

    private void moremedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moremedActionPerformed
        
        num = Double.parseDouble(screen_display.getText());
         calculation =1;
// TODO add your handling code here:
    }//GEN-LAST:event_moremedActionPerformed

    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
        
        if(screen_display.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Cannot be Empty");
    }else{
     arthmetic_operations();
    } 
        // TODO add your handling code here:
    }//GEN-LAST:event_finishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton cancel;
    private javax.swing.JButton clear;
    private javax.swing.JComboBox<String> display;
    private javax.swing.JButton finish;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField medquantity;
    private javax.swing.JButton moremed;
    private javax.swing.JButton ok;
    private javax.swing.JComboBox<String> patientname;
    private javax.swing.JButton print;
    private javax.swing.JButton receipt;
    private javax.swing.JTextArea screen;
    private javax.swing.JTextField screen_display;
    // End of variables declaration//GEN-END:variables
}
