/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pceaturidispensary;

import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import pceaturidispensary.hospital;
import pceaturidispensary.Login;
import javax.swing.JOptionPane;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import static pceaturidispensary.Login.conn;
/**
 *
 * @author hp
 */
public class settings extends javax.swing.JFrame {

    /**
     * Creates new form settings
     */
    public settings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        oldusername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        newusername = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        oldpassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        newpassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        change = new javax.swing.JButton();
        confirm = new javax.swing.JButton();
        back = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1110, 650));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(224, 0, 255));
        jLabel2.setText("SETTINGS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(418, 11, 217, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(224, 0, 255));
        jLabel3.setText("CHANGE SYSTEM PASSWORD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(248, 67, 545, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("ENTER OLD USERNAME AND PASSWORD");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 150, 476, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setText("ENTER NEW USERNAME AND PASSWORD");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 150, 384, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("OLD USERNAME");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(250, 200, 220, 30);

        oldusername.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        oldusername.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(oldusername);
        oldusername.setBounds(480, 190, 340, 60);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("NEW USERNAME");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 190, 210, 40);

        newusername.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        newusername.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(newusername);
        newusername.setBounds(480, 190, 340, 60);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("OLD PASSWORD");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(250, 310, 210, 29);

        oldpassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        oldpassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(oldpassword);
        oldpassword.setBounds(480, 300, 340, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("NEW PASSWORD");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(240, 300, 210, 40);

        newpassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        newpassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(newpassword);
        newpassword.setBounds(480, 300, 340, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel4.setText("CONFIRM OLD USERNAME AND PASSWORD ARE CORRECT");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 390, 489, 20);

        change.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        change.setText("CHANGE");
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });
        getContentPane().add(change);
        change.setBounds(540, 430, 150, 50);

        confirm.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        confirm.setText("CONFIRM");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        getContentPane().add(confirm);
        confirm.setBounds(540, 430, 150, 50);

        back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        back.setText("<-BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(340, 430, 130, 50);

        clear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clear.setText("CLEAR");
        getContentPane().add(clear);
        clear.setBounds(730, 430, 120, 50);

        jLabel12.setForeground(new java.awt.Color(102, 51, 255));
        jLabel12.setText("Purposely made for PCEA Turi Dispensary by Simon Muiruri");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(430, 540, 410, 14);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\pceaturidispensary\\image\\stethescope.png")); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-160, -160, 1300, 760);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public Connection getConnection(){
    try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary", "root", "");
            return conn;
            
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
}
public boolean checkDetails(String usr, String  pwd){
        
        try {
            conn = getConnection();
            
            PreparedStatement ps;
            ps = conn.prepareStatement("SELECT * FROM login WHERE username = ? AND password = ?");
            ps.setString(1, usr);
            ps.setString(2, pwd);
            
            ResultSet result = ps.executeQuery();
            
            return result.next();
            
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
        
        
    }
public void updatedetails(String nusername, String npassword){
       
        Connection conn = Login.conn;               
        try {           
            
            PreparedStatement ps;
           ps = conn.prepareStatement("UPDATE login SET username = ? , password = ?" );
            ps.setString(1, nusername);
            ps.setString(2, npassword);
            
          ps.execute();
          ps.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex);

        }
        
        
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       jLabel5.setVisible(false);
       jLabel6.setVisible(false);
       jLabel7.setVisible(false);
       newusername.setVisible(false);
       newpassword.setVisible(false);
       change.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        String password = oldpassword.getText();
        String username = oldusername.getText();
        String usr = oldusername.getText();
        String pwd = oldpassword.getText();
        if(checkDetails(usr, pwd)){
            
            JOptionPane.showMessageDialog(null, "You are about to change USERNAME and PASSWORD");
       jLabel5.setVisible(true);
       jLabel6.setVisible(true);
       jLabel7.setVisible(true);
       newusername.setVisible(true);
       newpassword.setVisible(true);
       change.setVisible(true);
       
       jLabel1.setVisible(false);
       jLabel4.setVisible(false);
       confirm.setVisible(false);
       jLabel8.setVisible(false);
       jLabel9.setVisible(false);
       oldusername.setVisible(false);
       oldpassword.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "!Wrong USERNAME and PASSWORD!", " Error", JOptionPane.ERROR_MESSAGE);
            oldusername.setText("");
            oldpassword.setText("");

        }
        
        // TODO add your handling code here:
        
    }//GEN-LAST:event_confirmActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        hospital settings = new hospital();
        settings.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        String nusername = newusername.getText();
        String npassword = newpassword.getText();
        updatedetails( nusername,  npassword);     
        JOptionPane.showMessageDialog(null, "USERNAME and PASSWORD changed successfully");
       Login settings = new Login();
       settings.setVisible(true);
       dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_changeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton change;
    private javax.swing.JButton clear;
    private javax.swing.JButton confirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField newpassword;
    private javax.swing.JTextField newusername;
    private javax.swing.JPasswordField oldpassword;
    private javax.swing.JTextField oldusername;
    // End of variables declaration//GEN-END:variables
}
