/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pceaturidispensary;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class updateLabCharges extends javax.swing.JFrame {

    /**
     * Creates new form updateLabCharges
     */
    public updateLabCharges() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selector = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        selector.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorActionPerformed(evt);
            }
        });
        getContentPane().add(selector);
        selector.setBounds(10, 116, 160, 32);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Select the service you want to change its price");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 40, 330, 16);

        price.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        getContentPane().add(price);
        price.setBounds(210, 120, 163, 29);

        add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add.setText("UPDATE");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(160, 190, 110, 31);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("price");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 90, 70, 16);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\pceaturidispensary\\image\\stethescope.png")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-50, -10, 460, 310);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 public void showtable(){
       try{
           Connection conn;
           Statement st;
           ResultSet rs;
           
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary" , "root", "");
            st = conn.createStatement();
            String s = "select * from laboratory ORDER BY id DESC";
            rs = st.executeQuery(s);
            while(rs.next()){
                selector.addItem(rs.getString(2));
            }
            
            
        }catch(SQLException e){
            
        } 
   }
    
    
    private void Fillcombo(){
        try{
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary" , "root", "");
            String sql = "select * from laboratory";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            stmt = conn.prepareStatement(sql);
            rs=stmt.executeQuery();
            while (rs.next()){
                String name = rs.getString("service");
                selector.addItem(name);
            }
            
        }catch(SQLException e){
            
        }
    }
    
    private void selectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorActionPerformed
        //price.setText(selector.getSelectedItem().toString());
    }//GEN-LAST:event_selectorActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
     if(price.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "The quantity cannot be empty, Please Fill", "Empty blank!", JOptionPane.ERROR_MESSAGE);
            
        }
        else{
            
        
        try{
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pceaturidispensary" , "root", "");
            PreparedStatement ps;
//           
            String sql =  "update  laboratory set charges = ? where service = ? ";
            PreparedStatement stmt = conn.prepareStatement(sql);
            
            
            try{
                int x = Integer.parseInt(price.getText());
                if(x <= 0){
                    JOptionPane.showMessageDialog(null, "Value too low","Error", JOptionPane.ERROR_MESSAGE);
                    
                }
                else{
                    stmt.setInt(1, x);
                }
                
                
            }
            catch(NumberFormatException exe){
                JOptionPane.showMessageDialog(null, "Please Check the  Quantity", "Error", JOptionPane.ERROR_MESSAGE);
            }
            String value = selector.getSelectedItem().toString();
            stmt.setString(2, value);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Saved", "success", JOptionPane.INFORMATION_MESSAGE);
            laboratory updateLabCharges = new laboratory();
            updateLabCharges.setVisible(true);
            dispose();
        }catch(SQLException exe){
            JOptionPane.showMessageDialog(null, exe);
        }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    showtable();
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateLabCharges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateLabCharges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateLabCharges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateLabCharges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateLabCharges().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField price;
    private javax.swing.JComboBox<String> selector;
    // End of variables declaration//GEN-END:variables
}
